#Yml file to provision with Ansible. On the backupweb1 and backupweb2 VM, install 
#apache2, copy a custom index, enable the apache2 service, restart the 
#apache2 service, and run a test. On the Haproxy VM install haproxy, 
#copy the haproxy.cfg file, enable the haproxy service, restart the 
#haproxy service and perform a test.
---
- hosts: phaproxy
  remote_user: remoto
  become_user: root
  become: true
  tasks:
    - name: iniciar el servicio de lxd en vm severLoadBalancer
      shell: sudo systemctl start lxd
    - name: habilitar el servicio de lxd en vm severLoadBalancer
      shell: sudo systemctl enable lxd
    - name: reiniciar el servicio de lxd en vm severLoadBalancer
      shell: sudo systemctl restart lxd
    - name: encender contenedor web1 en en vm severLoadBalancer
      shell: lxc start balancer