#Yml file to provision with Ansible. On the backupweb1 and backupweb2 VM, install 
#apache2, copy a custom index, enable the apache2 service, restart the 
#apache2 service, and run a test. On the Haproxy VM install haproxy, 
#copy the haproxy.cfg file, enable the haproxy service, restart the 
#haproxy service and perform a test.
---
- hosts: pweb1
  remote_user: remoto
  become_user: root
  become: true
  tasks:
    - name: encender contenedor web1 en vm severWeb1
      shell: lxc start web1
    - name: encender contenedor backupweb1 en vm severWeb1
      shell: lxc start backupweb1
- hosts: pweb2
  remote_user: remoto
  become_user: root
  become: true
  tasks:
    - name: encender contenedor web2 en vm severWeb2
      shell: lxc start web2
    - name: encender contenedor backupweb2 en vm severWeb2
      shell: lxc start backupweb2